from __future__ import annotations

import datetime as dt

from sec_report_kit.models import Finding
from sec_report_kit.report.html_renderer import render_consolidated_dashboard_report, render_html_report


EMPTY_COUNTS = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "UNKNOWN": 0}


def _finding(severity="HIGH", primary_url="https://example.com"):
    return Finding(
        source_type="test",
        target="myimage:1",
        severity=severity,
        vulnerability_id="CVE-2024-0001",
        package="openssl",
        installed_version="1.0",
        fixed_version="1.1",
        title="Test vuln",
        primary_url=primary_url,
    )


def test_render_html_with_finding_with_url():
    counts = {**EMPTY_COUNTS, "HIGH": 1}
    html = render_html_report(
        target_ref="myimage:1",
        source_label="trivy",
        findings=[_finding(primary_url="https://example.com")],
        counts=counts,
    )
    assert '<div class="meta">Source: <strong>trivy</strong> | Target: <strong>myimage:1</strong>' in html
    assert "CVE-2024-0001" in html
    assert "https://example.com" in html
    assert "openssl" in html
    assert "This report is generated by" in html
    assert "sec-report-kit utility" in html
    assert "Connect with the developer:" in html
    assert ">Shan Konduru<" in html
    assert "https://github.com/ShanKonduru/sec-report-kit" in html
    assert "https://www.linkedin.com/in/shankonduru/" in html


def test_render_html_with_finding_no_url():
    counts = {**EMPTY_COUNTS, "HIGH": 1}
    html = render_html_report(
        target_ref="myimage:1",
        source_label="trivy",
        findings=[_finding(primary_url="")],
        counts=counts,
    )
    assert "CVE-2024-0001" in html
    # no anchor tag when url is empty
    assert 'href=""' not in html


def test_render_html_no_findings():
    html = render_html_report(
        target_ref="myimage:1",
        source_label="trivy",
        findings=[],
        counts=EMPTY_COUNTS,
    )
    assert "No vulnerabilities found" in html


def test_render_html_escapes_special_chars():
    finding = Finding(
        source_type="test",
        target='target<script>alert(1)</script>',
        severity="LOW",
        vulnerability_id="CVE-X",
        package='pkg"quoted"',
        installed_version="1.0",
        fixed_version="-",
        title="<b>bold</b>",
        primary_url="",
    )
    counts = {**EMPTY_COUNTS, "LOW": 1}
    html = render_html_report(
        target_ref="ref",
        source_label="test",
        findings=[finding],
        counts=counts,
    )
    assert "<script>alert(1)</script>" not in html
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in html


def test_render_consolidated_dashboard_with_available_and_missing_reports(tmp_path):
    reports_dir = tmp_path / "reports"
    output_dir = tmp_path / "out"
    reports_dir.mkdir()
    output_dir.mkdir()

    (reports_dir / "bandit-report.html").write_text("<html>bandit</html>", encoding="utf-8")
    (output_dir / "trivy-report.html").write_text("<html>trivy</html>", encoding="utf-8")

    findings = [
        Finding(
            source_type="bandit",
            target="src/app.py",
            severity="HIGH",
            vulnerability_id="B101",
            package="-",
            installed_version="-",
            fixed_version="-",
            title="Assert used",
            primary_url="",
        ),
        Finding(
            source_type="trivy",
            target="requirements.txt",
            severity="CRITICAL",
            vulnerability_id="CVE-1",
            package="urllib3",
            installed_version="2.6.3",
            fixed_version="2.7.0",
            title="Critical vuln",
            primary_url="",
        ),
        Finding(
            source_type="pip-audit",
            target="requirements.txt",
            severity="MEDIUM",
            vulnerability_id="GHSA-1",
            package="requests",
            installed_version="2.0.0",
            fixed_version="2.1.0",
            title="Dependency finding",
            primary_url="",
        ),
    ]

    html = render_consolidated_dashboard_report(
        target_ref="repo-root",
        findings=findings,
        counts={"CRITICAL": 1, "HIGH": 1, "MEDIUM": 1, "LOW": 0, "UNKNOWN": 0},
        reports_dir=reports_dir,
        output_dir=output_dir,
    )

    assert 'href="../reports/bandit-report.html"' in html
    assert 'src="trivy-report.html"' in html
    assert "Open Full Report" in html
    assert "Generate this report first using scripts/render_pip_audit_html.sh or scripts/render_pip_audit_html.bat." in html
    assert "scripts/render_pip_audit_html.sh" in html
    assert "Bandit Report" in html
    assert "Trivy Report" in html
    assert "Reports available:" in html
    assert "This report is generated by" in html
    assert "sec-report-kit utility" in html
    assert "Connect with the developer:" in html


def test_render_consolidated_dashboard_shows_all_tools_when_no_visible_tools(tmp_path):
    reports_dir = tmp_path / "reports"
    output_dir = tmp_path / "out"
    reports_dir.mkdir()
    output_dir.mkdir()

    html = render_consolidated_dashboard_report(
        target_ref="repo-root",
        findings=[],
        counts={"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "UNKNOWN": 0},
        reports_dir=reports_dir,
        output_dir=output_dir,
    )

    assert "pip-audit Report" in html
    assert "GitLeaks Report" in html
    assert "TruffleHog Report" in html
    assert "Generate this report first using scripts/render_trivy_html.sh or scripts/render_trivy_html.bat." in html


def test_render_consolidated_dashboard_date_filter_excludes_old_html_files(tmp_path):
    """HTML report files outside the date range must not appear as 'available'."""
    reports_dir = tmp_path / "reports"
    output_dir = reports_dir
    reports_dir.mkdir()

    # Write a bandit HTML file and backdate its mtime to 2000-01-01
    bandit_html = reports_dir / "bandit-report.html"
    bandit_html.write_text("<html>bandit</html>", encoding="utf-8")
    old_mtime = dt.datetime(2000, 1, 1, tzinfo=dt.timezone.utc).timestamp()
    import os
    os.utime(bandit_html, (old_mtime, old_mtime))

    # Write a trivy HTML file with a very-future mtime (3000-01-01)
    trivy_html = reports_dir / "trivy-report.html"
    trivy_html.write_text("<html>trivy</html>", encoding="utf-8")
    future_mtime = dt.datetime(3000, 1, 1, tzinfo=dt.timezone.utc).timestamp()
    os.utime(trivy_html, (future_mtime, future_mtime))

    tz = dt.timezone.utc
    since = dt.datetime(2026, 1, 1, tzinfo=tz)
    until = dt.datetime(2026, 12, 31, 23, 59, 59, tzinfo=tz)

    html = render_consolidated_dashboard_report(
        target_ref="repo",
        findings=[],
        counts={"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "UNKNOWN": 0},
        reports_dir=reports_dir,
        output_dir=output_dir,
        modified_since=since,
        modified_until=until,
    )

    # Bandit HTML is from 2000 (before since) — must NOT be shown as available
    assert 'src="../reports/bandit-report.html"' not in html
    assert 'src="bandit-report.html"' not in html
    # Trivy HTML is from 3000 (after until) — must NOT be shown as available
    assert 'src="trivy-report.html"' not in html
    # Since and until labels should appear in the hero
    assert "Since: 2026-01-01" in html
    assert "Until: 2026-12-31" in html


def test_render_consolidated_dashboard_filtered_mode_requires_included_source(tmp_path):
    reports_dir = tmp_path / "reports"
    reports_dir.mkdir()

    bandit_html = reports_dir / "bandit-report.html"
    bandit_html.write_text("<html>bandit</html>", encoding="utf-8")

    html = render_consolidated_dashboard_report(
        target_ref="repo",
        findings=[],
        counts={"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "UNKNOWN": 0},
        reports_dir=reports_dir,
        output_dir=reports_dir,
        modified_since=dt.datetime(2026, 5, 17, tzinfo=dt.timezone.utc),
        modified_until=dt.datetime(2026, 5, 20, 23, 59, 59, tzinfo=dt.timezone.utc),
        included_sources=set(),
    )

    assert "Reports available: 0/11" in html
    assert 'src="bandit-report.html"' not in html
    assert "Tool report not found" in html
