name: Trivy Filesystem Audit

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 9 * * 1"

permissions:
  contents: read

jobs:
  trivy-fs-scan:
    name: Trivy filesystem scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN || github.token }}

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          exit-code: "1"
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM
